### ISSUE TITLE
yooo man, found a use case that you need to show the results for... 😰

### ISSUE THREAD

**Issue by PS2emu** [MichaelDimmitt/javascript-simple-terminal#1]
node nextAttempt.js ping 8.8.8.8

**Comment by MichaelDimmitt** [comment]
@PS2emu, just learning about the existence of this issue.

Recently switched the project to use exec and now everything is in a test file.

Added your particular use-case to the test suite: ( let me know if there is anything else 🙂 )
https://github.com/MichaelDimmitt/simp-js_term/blob/add-ping-test/terminal.test.js#L69
